# Generated by Django 5.0.6 on 2024-08-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivedocuments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='direction',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
