# Generated by Django 5.0.6 on 2024-08-08 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boite',
            fields=[
                ('id_boite', models.AutoField(db_column='id_boite', primary_key=True, serialize=False)),
                ('mention', models.CharField(max_length=150)),
                ('numero_rang', models.CharField(default='Aucune', max_length=150)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('id_user', models.IntegerField(db_column='id_user')),
                ('etat', models.IntegerField(default=1)),
                ('harmoire', models.CharField(default='Aucune', max_length=150)),
                ('numero_comp', models.CharField(default='Aucune', max_length=50)),
                ('niveau', models.CharField(default='Aucune', max_length=50)),
                ('commentaire', models.CharField(default='Aucun', max_length=255)),
            ],
            options={
                'db_table': 'Boite',
            },
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id_dmd', models.AutoField(db_column='id_dmd', primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('commentaire', models.CharField(max_length=255)),
                ('commentaire_reponse', models.CharField(max_length=255, null=True)),
                ('date_dmd', models.DateField(auto_now_add=True)),
                ('date_retour', models.DateField(null=True)),
                ('id_demandeur', models.IntegerField(db_column='id_demandeur')),
                ('id_accepteur', models.IntegerField(db_column='id_acepteur', null=True)),
                ('etat', models.IntegerField(default=0)),
                ('id_docuement', models.IntegerField(db_column='id_document', null=True)),
                ('id_boite', models.IntegerField(db_column='id_boite', null=True)),
            ],
            options={
                'db_table': 'Demande',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id_document', models.AutoField(db_column='id_document', primary_key=True, serialize=False)),
                ('numero_docuemnt', models.CharField(max_length=150)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('date_destruction', models.DateField(null=True)),
                ('bl', models.CharField(default='BL', max_length=255, null=True)),
                ('chemin_acces', models.CharField(max_length=255)),
                ('disponibilite', models.IntegerField(default=0)),
                ('eta', models.DateField(default=datetime.datetime(2024, 8, 8, 17, 57, 57, 965458))),
                ('client', models.CharField(max_length=40, null=True)),
                ('nom_navire', models.CharField(max_length=100, null=True)),
                ('numero_voyage', models.CharField(max_length=100, null=True)),
                ('id_us', models.IntegerField(db_column='id_us', null=True)),
                ('id_boite', models.IntegerField(db_column='id_boite', null=True)),
                ('id_per', models.IntegerField(db_column='id_per', default=2, null=True)),
            ],
            options={
                'db_table': 'Document',
            },
        ),
        migrations.CreateModel(
            name='RestrictionDocument',
            fields=[
                ('id_restric', models.AutoField(db_column='id_dmd', primary_key=True, serialize=False)),
                ('id_user', models.IntegerField()),
                ('id_doc', models.IntegerField()),
                ('numero_docuent', models.CharField(default='numero_doc', max_length=255)),
                ('service', models.CharField(default='service', max_length=255)),
                ('date_dmd', models.DateField(null=True)),
                ('etat', models.IntegerField(default=1)),
                ('dmd', models.IntegerField(default=0)),
                ('ref', models.IntegerField(default=0)),
                ('acces_dir', models.IntegerField(default=0)),
                ('acces', models.CharField(max_length=150)),
                ('id_chef', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Restriction',
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_utilisateur', models.AutoField(db_column='id_user', primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('etat', models.IntegerField(default=1)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('direction', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Utilisateur',
            },
        ),
    ]
