# Generated by Django 5.0.6 on 2024-07-29 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='eta',
            field=models.DateField(default=datetime.datetime(2024, 7, 29, 14, 54, 42, 191517)),
        ),
    ]
