# Generated by Django 3.1.13 on 2024-05-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0002_mig12'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='bl',
            field=models.CharField(default='BL', max_length=255, null=True),
        ),
    ]
