# Generated by Django 3.1.13 on 2024-05-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0003_mig13'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='etat',
            field=models.IntegerField(default=1),
        ),
    ]
