# Generated by Django 3.1.13 on 2024-05-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0005_mig15'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictiondocument',
            name='etat',
            field=models.IntegerField(default=1),
        ),
    ]
