# Generated by Django 3.1.13 on 2024-05-28 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0007_mig18'),
    ]

    operations = [
        migrations.AddField(
            model_name='restrictiondocument',
            name='date_dmd',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='restrictiondocument',
            name='numero_docuent',
            field=models.CharField(default='numero_doc', max_length=255),
        ),
        migrations.AddField(
            model_name='restrictiondocument',
            name='service',
            field=models.CharField(default='service', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='eta',
            field=models.DateField(default=datetime.datetime(2024, 5, 28, 10, 34, 36, 182262)),
        ),
    ]
