# Generated by Django 5.0.6 on 2024-08-12 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0009_alter_document_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='eta',
            field=models.DateField(default=datetime.datetime(2024, 8, 12, 11, 40, 16, 692757)),
        ),
    ]
