# Generated by Django 5.0.6 on 2024-08-13 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0011_alter_document_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='eta',
            field=models.DateField(default=datetime.datetime(2024, 8, 13, 19, 37, 58, 105981)),
        ),
    ]
