# Generated by Django 5.0.6 on 2024-08-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturations', '0012_alter_document_eta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='eta',
            field=models.DateTimeField(null=True),
        ),
    ]
